# Build settings

source: .
destination: ./_site
markdown: kramdown
# don't change the following; coderay will break the embedded
# annotations.
kramdown:
  enable_coderay: false
permalinks: pretty
# safe: true
markdown_ext: md

##############################################################################

# Site settings

name: Numerical Atlas
baseurl: "/annodoc"
homeurl: "https://github.com/gebodal/annodoc/"
editurl: "https://github.com/gebodal/annodoc/edit/gh-pages"
issueurl: "https://github.com/gebodal/annodoc/issues"

##############################################################################

# Collection settings

collections:
  entity:
    output: true
  relation:
    output: true

theme: jekyll-theme-slate
